// #####  Color Palette by Paletton.com
// #####  Palette URL: http://paletton.com/#uid=15A0u0knE++48+AfW+svG++++Tu


// *** Primary color:

//    shade 0 = #FF4350 = rgb(255, 67, 80) = rgba(255, 67, 80,1) = rgb0(1,0.263,0.314)
//    shade 1 = #FFDEE0 = rgb(255,222,224) = rgba(255,222,224,1) = rgb0(1,0.871,0.878)
//    shade 2 = #FF8089 = rgb(255,128,137) = rgba(255,128,137,1) = rgb0(1,0.502,0.537)
//    shade 3 = #FF0315 = rgb(255,  3, 21) = rgba(255,  3, 21,1) = rgb0(1,0.012,0.082)
//    shade 4 = #FD0013 = rgb(253,  0, 19) = rgba(253,  0, 19,1) = rgb0(0.992,0,0.075)


// #####  Generated by Paletton.com (c) 2002-2014

// /* CSS - Cascading Style Sheet */
// /* Palette color codes */
// /* Palette URL: http://paletton.com/#uid=15A0u0knE++48+AfW+svG++++Tu */

// /* Feel free to copy&paste color codes to your application */


// /* As hex codes */

// .color-primary-0 { color: #FF4350 }	/* Main Primary color */
// .color-primary-1 { color: #FFDEE0 }
// .color-primary-2 { color: #FF8089 }
// .color-primary-3 { color: #FF0315 }
// .color-primary-4 { color: #FD0013 }



// /* As RGBa codes */

// .rgba-primary-0 { color: rgba(255, 67, 80,1) }	/* Main Primary color */
// .rgba-primary-1 { color: rgba(255,222,224,1) }
// .rgba-primary-2 { color: rgba(255,128,137,1) }
// .rgba-primary-3 { color: rgba(255,  3, 21,1) }
// .rgba-primary-4 { color: rgba(253,  0, 19,1) }



// /* Generated by Paletton.com © 2002-2014 */
// /* http://paletton.com */