export const FETCHING_USER = 'FETCHING_USER';
export const FETCHED_USER = 'FETCHED_USER';
export const SET_USER = 'SET_USER';
export const UNSET_USER = 'UNSET_USER';
export const FETCHING_USER_ERROR = 'FETCHING_USER_ERROR';

// TEST ACTIONS
export const FETCHING = 'FETCHING';
export const FETCHED = 'FETCHED';

// CAMERA ACTIONS
export const SCANNING = 'SCANNING';
export const SCANNED = 'SCANNED';
export const SCANNING_ERROR = 'SCANNING_ERROR';
export const UNSET_SCAN = 'UNSET_SCAN';
export const SET_BARCODES = 'SET_BARCODES';

// UPC API CALL
export const FETCHING_PRODUCT = 'FETCHING_PRODUCT';
export const FETCHED_PRODUCT = 'FETCHED_PRODUCT';
export const SET_PRODUCT = 'SET_PRODUCT';
export const FETCHING_PRODUCT_ERROR = 'FETCHING_PRODUCT_ERROR';
