export const FETCHING_USER = 'FETCHING_USER';
export const FETCHED_USER = 'FETCHED_USER';
export const SET_USER = 'SET_USER';
export const UNSET_USER = 'UNSET_USER';
export const FETCHING_USER_ERROR = 'FETCHING_USER_ERROR';

// TEST ACTIONS
export const FETCHING = 'FETCHING';
export const FETCHED = 'FETCHED';

// CAMERA ACTIONS
export const SCANNING = 'SCANNING';
export const SCANNED = 'SCANNED';
export const SCANNING_ERROR = 'SCANNING_ERROR';
export const UNSET_SCAN = 'UNSET_SCAN';
export const SET_BARCODES = 'SET_BARCODES';

// UPC API CALL
export const FETCHING_PRODUCT = 'FETCHING_PRODUCT';
export const FETCHED_PRODUCT = 'FETCHED_PRODUCT';
export const SET_PRODUCT = 'SET_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const FETCHING_PRODUCT_ERROR = 'FETCHING_PRODUCT_ERROR';

// PANTRY API CALL
export const FETCHING_FOOD_ITEMS = 'FETCHING_FOOD_ITEMS';
export const FETCHED_FOOD_ITEMS = 'FETCHED_FOOD_ITEMS';
export const SET_FOOD_ITEMS = 'SET_FOOD_ITEMS';
export const FETCHING_FOOD_ITEMS_ERROR = 'FETCHING_FOOD_ITEMS_ERROR';

// SCANNING RECEIPT
export const SCANNING_RECEIPT = 'SCANNING_RECEIPT';
export const SCANNED_RECEIPT = 'SCANNED_RECEIPT';
export const SCANNING_RECEIPT_ERROR = 'SCANNING_RECEIPT_ERROR';
export const SET_ITEM = 'SET_ITEM';
export const UNSET_RECEIPT_ITEM = 'UNSET_RECEIPT_ITEM';

// APP ACTION TYPES
export const CHANGE_CONNECTION_STATUS = 'CHANGE_CONNECTION_STATUS';
export const FETCHING_CONNECTION_STATE = 'FETCHING_CONNECTION_STATE';
