import { StyleSheet } from 'react-native';

export const dashBoardStyles = StyleSheet.create({
  button: {
    backgroundColor: 'rgba(28,42,56,0.8)',
    borderRadius: 100,
    height: 40,
    marginLeft: 22,
    marginTop: 25,
    opacity: 0.76,
    width: 40,
  },
  container: {
    // backgroundColor: '#1c2a38',
    height: '40%',
    width: '100%',
  },
  edit_button: {
    alignSelf: 'center',
    color: '#8596a3',
    fontSize: 14,
    lineHeight: 20,
  },
  image: {
    height: 432,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  imageStack: {
    height: 181,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  imageStackStack: {
    height: 141,
  },
  location: {
    color: 'white',
    fontSize: 16,
    height: 20,
    lineHeight: 20,
    width: 130,
  },
  metadata: {
    flexDirection: 'row',
    height: 20,
    justifyContent: 'center',
    marginLeft: 22,
    marginRight: 40,
    // marginTop: 98,
  },
  navContainer: {
    alignItems: 'center',
    backgroundColor: '#fff',
    height: 600,
    paddingTop: 5,
    position: 'relative',
  },
  nav_button: {
    alignItems: 'center',
    backgroundColor: '#ff5c61',
    borderRadius: 50,
    marginVertical: 10,
    padding: 12,
    width: '90%',
    // width: windowWidth - 200,
  },
  time: {
    color: 'white',
    fontSize: 16,
    lineHeight: 20,
  },
  welcome: {
    alignSelf: 'center',
    color: 'rgba(255,255,255,1)',
    fontSize: 24,
    height: 50,
    lineHeight: 30,
    marginTop: -102,
  },
});
